# LinkedIn PPT Generator Service
# Task 3.2.1: LinkedIn PPT Generator Service

services:
  linkedin-ppt-generator:
    build: .
    container_name: linkedin-ppt-generator
    ports:
      - "8002:8002"
    environment:
      - HOST=0.0.0.0
      - PORT=8002
      - PRESENTON_SERVICE_URL=http://host.docker.internal:8089
      - PRESENTON_TIMEOUT=60.0
      - DEBUG=false
    restart: unless-stopped