global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kolegium-monitor'

# Rule files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Knowledge Base metrics
  - job_name: 'knowledge-base'
    static_configs:
      - targets: ['knowledge-base:9090']
    metrics_path: '/metrics'

  # Kolegium API metrics
  - job_name: 'kolegium-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'

  # CrewAI Agents metrics
  - job_name: 'content-scout'
    static_configs:
      - targets: ['content-scout:8001']
    metrics_path: '/metrics'

  - job_name: 'trend-analyst'
    static_configs:
      - targets: ['trend-analyst:8002']
    metrics_path: '/metrics'

  - job_name: 'editorial-strategist'
    static_configs:
      - targets: ['editorial-strategist:8003']
    metrics_path: '/metrics'

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Postgres exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093