[project]
name = "ai_kolegium_redakcyjne"
version = "0.1.0"
description = "Vector Wave - AI Kolegium Redakcyjne using CrewAI"
authors = [{ name = "Vector Wave Team", email = "team@vectorwave.ai" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.30.11",
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.27.0",
    "redis>=5.0.1",
    "asyncpg>=0.29.0",
    "sqlalchemy>=2.0.25",
    "websockets>=12.0",
    "pydantic>=2.5.3",
    "prometheus-client>=0.19.0",
    "python-multipart>=0.0.6",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "httpx>=0.25.2",
    "langchain-openai>=0.1.7",
    "langchain-anthropic>=0.1.15"
]

[project.scripts]
ai_kolegium_redakcyjne = "ai_kolegium_redakcyjne.main:run"
run_crew = "ai_kolegium_redakcyjne.main:run"
train = "ai_kolegium_redakcyjne.main:train"
replay = "ai_kolegium_redakcyjne.main:replay"
test = "ai_kolegium_redakcyjne.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
