services:
  publishing-orchestrator:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - AI_WRITING_FLOW_URL=http://host.docker.internal:8001
      - LINKEDIN_PPT_GENERATOR_URL=http://host.docker.internal:8002
      - EDITORIAL_SERVICE_URL=http://host.docker.internal:8040
    volumes:
      - ./src:/app/src:ro
    networks:
      - vector-wave-dev
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8050/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vector-wave-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  vector-wave-dev:
    driver: bridge